"""Initial migration (students table)

Revision ID: 03fa4d8bd5ba
Revises: 79c7329c79e5
Create Date: 2025-04-22 18:14:35.802644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fa4d8bd5ba'
down_revision = '79c7329c79e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=True))
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
