"""Initial migration (students table)

Revision ID: 9a1d91ed8e8f
Revises: 03fa4d8bd5ba
Create Date: 2025-04-22 18:23:24.610778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1d91ed8e8f'
down_revision = '03fa4d8bd5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=True))
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
